# Generated by Django 2.0.6 on 2018-08-08 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('household', '0002_auto_20180802_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fallow.Crop')),
            ],
        ),
        migrations.CreateModel(
            name='Declare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='household.Member')),
            ],
        ),
        migrations.CreateModel(
            name='FallowTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsidy', models.IntegerField(null=True)),
                ('period', models.CharField(max_length=1, null=True)),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fallow.Crop')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='household.Member')),
            ],
        ),
        migrations.CreateModel(
            name='RiceArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField(null=True)),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fallow.Crop')),
                ('declare', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fallow.Declare')),
            ],
        ),
        migrations.CreateModel(
            name='TransferCrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fallow.Crop')),
                ('rice_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fallow.RiceArea')),
            ],
        ),
    ]
