# Generated by Django 2.0.9 on 2018-11-21 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fallow', '0004_fallowtransfer_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ricearea',
            name='declare',
        ),
        migrations.RemoveField(
            model_name='transfercrop',
            name='rice_area',
        ),
        migrations.AddField(
            model_name='transfercrop',
            name='declare',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fallow.Declare', verbose_name='Declare'),
            preserve_default=False,
        ),
    ]
