# Generated by Django 2.0.9 on 2018-11-30 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fallow', '0005_auto_20181121_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declare',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declares', to='household.Member', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='declare',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='declares', to='household.Year', verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='fallowtransfer',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallow_transfer', to='fallow.Crop', verbose_name='Crop'),
        ),
        migrations.AlterField(
            model_name='fallowtransfer',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallow_transfer', to='household.Member', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='ricearea',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rice_areas', to='fallow.Crop', verbose_name='Crop'),
        ),
        migrations.AlterField(
            model_name='transfercrop',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_crops', to='fallow.Crop', verbose_name='Crop'),
        ),
        migrations.AlterField(
            model_name='transfercrop',
            name='declare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_crops', to='fallow.Declare', verbose_name='Declare'),
        ),
    ]
