# Generated by Django 2.0.6 on 2018-08-08 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0002_auto_20180802_1553'),
        ('small_big', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantlist',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_list_owner', to='household.Member'),
        ),
        migrations.AlterField(
            model_name='tenantlist',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_list_member', to='household.Member'),
        ),
    ]
