# Generated by Django 2.0.6 on 2018-08-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='season',
            field=models.CharField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')], max_length=1, verbose_name='Season'),
        ),
        migrations.DeleteModel(
            name='Seasons',
        ),
    ]
