# Generated by Django 2.0.6 on 2018-09-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_auto_20180817_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
    ]
