# Generated by Django 2.0.6 on 2018-09-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_auto_20180903_1404'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnimalCount',
            new_name='Profile',
        ),
    ]
