# Generated by Django 2.0.9 on 2018-11-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0005_auto_20181114_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestock',
            name='code',
            field=models.CharField(default='default', max_length=12, verbose_name='Code'),
        ),
    ]
