# Generated by Django 2.0.9 on 2018-11-30 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0008_auto_20181121_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counttype',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='investigation',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='investigationtype',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('id',)},
        ),
    ]
