# Generated by Django 2.0.9 on 2018-11-30 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0009_auto_20181130_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='household.Member', verbose_name='Member'),
        ),
    ]
