# Generated by Django 2.0.9 on 2018-11-30 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0010_auto_20181130_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='count_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='livestock.CountType', verbose_name='Count Type'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='livestock.Field', verbose_name='Field'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='investigation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='livestock.Investigation', verbose_name='Investigation'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='livestock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='livestock.Livestock', verbose_name='Livestock'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='household.Member', verbose_name='Member'),
        ),
    ]
