# Generated by Django 2.0.6 on 2018-09-03 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fallow', '0001_initial'),
        ('household', '0003_auto_20180816_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField(verbose_name='Area')),
                ('subsidy', models.IntegerField(verbose_name='Subsidy')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fallow.Crop', verbose_name='Livestock')),
            ],
        ),
        migrations.CreateModel(
            name='DisasterEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='disaster',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disaster.DisasterEvent', verbose_name='Field'),
        ),
        migrations.AddField(
            model_name='disaster',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.Member', verbose_name='Investigation'),
        ),
    ]
