# Generated by Django 2.0.6 on 2018-09-04 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='area',
            field=models.PositiveIntegerField(verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fallow.Crop', verbose_name='Crop'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disaster.DisasterEvent', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.Member', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='subsidy',
            field=models.PositiveIntegerField(verbose_name='Subsidy'),
        ),
    ]
