# Generated by Django 2.1.2 on 2018-11-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0003_auto_20180907_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='disasterevent',
            name='date',
            field=models.DateField(default='1911-01-01'),
        ),
        migrations.AlterField(
            model_name='disasterevent',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
