# Generated by Django 2.1.2 on 2018-11-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0004_auto_20181114_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='area',
            field=models.FloatField(verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='subsidy',
            field=models.FloatField(verbose_name='Subsidy'),
        ),
    ]
