# Generated by Django 2.1.2 on 2018-11-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0005_auto_20181116_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='subsidy',
            field=models.PositiveIntegerField(verbose_name='Subsidy'),
        ),
    ]
