# Generated by Django 2.0.9 on 2018-11-30 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0006_auto_20181120_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disasters', to='fallow.Crop', verbose_name='Crop'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disasters', to='disaster.DisasterEvent', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disasters', to='household.Member', verbose_name='Member'),
        ),
    ]
