# Generated by Django 2.0.6 on 2018-08-16 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('household', '0002_auto_20180802_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsidy', models.IntegerField(null=True, verbose_name='Subsidy')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.Member', verbose_name='Member')),
            ],
        ),
        migrations.CreateModel(
            name='LandlordRetire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsidy', models.IntegerField(null=True, verbose_name='Subsidy')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.Member', verbose_name='Member')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_member_set', to='household.Member', verbose_name='Member')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_owner_set', to='household.Member', verbose_name='Landlord')),
            ],
        ),
        migrations.CreateModel(
            name='TenantTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsidy', models.IntegerField(null=True, verbose_name='Subsidy')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.Member', verbose_name='Member')),
            ],
        ),
    ]
