# Generated by Django 2.1.2 on 2018-11-22 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smallbig', '0002_auto_20181120_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_member_set', to='household.Member', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_owner_set', to='household.Member', verbose_name='Landlord'),
        ),
    ]
