# Generated by Django 2.0.6 on 2018-08-30 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('household', '0003_auto_20180816_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElderlyAllowance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.Member', verbose_name='Member')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.Member', verbose_name='Member')),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('subsidy', models.IntegerField(verbose_name='subsidy')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.Member', verbose_name='Member')),
            ],
        ),
    ]
