# Generated by Django 2.1.2 on 2018-11-14 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0006_year'),
        ('welfare', '0002_auto_20180903_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='elderlyallowance',
            name='subsidy',
            field=models.IntegerField(default=0, verbose_name='subsidy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elderlyallowance',
            name='year',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='household.Year', verbose_name='Year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerinsurance',
            name='year',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='household.Year', verbose_name='Year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarship',
            name='year',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='household.Year', verbose_name='Year'),
            preserve_default=False,
        ),
    ]
