# Generated by Django 2.0.9 on 2018-11-30 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0003_auto_20181114_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elderlyallowance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elderly_allowances', to='household.Member', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='elderlyallowance',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elderly_allowances', to='household.Year', verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='farmerinsurance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_insurances', to='household.Member', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='farmerinsurance',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_insurances', to='household.Year', verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='household.Member', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='household.Year', verbose_name='Year'),
        ),
    ]
