# Generated by Django 2.0.6 on 2018-08-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='household_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
