# Generated by Django 2.1.2 on 2018-10-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0003_auto_20180816_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='household_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='app_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
