# Generated by Django 2.1.2 on 2018-11-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0004_auto_20181025_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='code',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
