# Generated by Django 2.1.2 on 2018-11-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0005_member_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
