# Generated by Django 2.0.9 on 2018-11-30 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0008_auto_20181115_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='household.Household'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='household.Role'),
        ),
    ]
